export const requests = [
  {
    id: 1,
    requesterName: "Aman Moa",
    deviceType: "Laptop",
    phoneNumber: "09-456-7890",
    email: "aman@example.com",
    status: "inprogress",
  },
  {
    id: 2,
    requesterName: "Kenna Pro",
    deviceType: "Printer",
    phoneNumber: "09-654-3210",
    email: "kenna@example.com",
    status: "accepted",
  },
  {
    id: 3,
    requesterName: "Naol Max",
    deviceType: "Network",
    phoneNumber: "09-654-3210",
    email: "naol@example.com",
    status: "accepted",
  },
  {
    id: 4,
    requesterName: "Miheret Pro",
    deviceType: "Hardware",
    phoneNumber: "09-654-3210",
    email: "miheret@example.com",
    status: "accepted",
  },
  {
    id: 5,
    requesterName: "Sarita Pro Max",
    deviceType: "software",
    phoneNumber: "09-654-3210",
    email: "sarita@example.com",
    status: "rejected",
  },
  {
    id: 6,
    requesterName: "Hana Smith",
    deviceType: "Tablet",
    phoneNumber: "09-789-1234",
    email: "hana@example.com",
    status: "inprogress",
  },
  {
    requesterName: "Liam Brown",
    deviceType: "Laptop",
    phoneNumber: "09-987-6543",
    email: "liam@example.com",
    status: "accepted",
  },
  {
    id: 7,
    requesterName: "Mia Wilson",
    deviceType: "Printer",
    phoneNumber: "09-345-6789",
    email: "mia@example.com",
    status: "rejected",
  },
  {
    id: 8,
    requesterName: "Noah Davis",
    deviceType: "Network",
    phoneNumber: "09-876-5432",
    email: "noah@example.com",
    status: "inprogress",
  },
  {
    id: 9,
    requesterName: "Emma Johnson",
    deviceType: "Hardware",
    phoneNumber: "09-234-5678",
    email: "emma@example.com",
    status: "accepted",
  },
  {
    id: 10,
    requesterName: "Olivia Martinez",
    deviceType: "Software",
    phoneNumber: "09-765-4321",
    email: "olivia@example.com",
    status: "rejected",
  },
  {
    id: 11,
    requesterName: "Sophia Lopez",
    deviceType: "Laptop",
    phoneNumber: "09-543-2109",
    email: "sophia@example.com",
    status: "accepted",
  },
  {
    id: 12,
    requesterName: "William Rodriguez",
    deviceType: "Printer",
    phoneNumber: "09-654-3210",
    email: "william@example.com",
    status: "inprogress",
  },
  {
    id: 13,
    requesterName: "Isabella Gonzalez",
    deviceType: "Network",
    phoneNumber: "09-321-6549",
    email: "isabella@example.com",
    status: "rejected",
  },
  {
    id: 14,
    requesterName: "James Martinez",
    deviceType: "Hardware",
    phoneNumber: "09-678-9123",
    email: "james@example.com",
    status: "accepted",
  },
  {
    id: 15,
    requesterName: "Elijah Hernandez",
    deviceType: "Software",
    phoneNumber: "09-567-8912",
    email: "elijah@example.com",
    status: "inprogress",
  },
  {
    id: 16,
    requesterName: "Ava King",
    deviceType: "Tablet",
    phoneNumber: "09-432-1098",
    email: "ava@example.com",
    status: "accepted",
  },
  {
    id: 17,
    requesterName: "Lucas Hill",
    deviceType: "Laptop",
    phoneNumber: "09-210-9876",
    email: "lucas@example.com",
    status: "rejected",
  },
  {
    id: 18,
    requesterName: "Mason Scott",
    deviceType: "Printer",
    phoneNumber: "09-678-3451",
    email: "mason@example.com",
    status: "inprogress",
  },
  {
    id: 19,
    requesterName: "Ethan Green",
    deviceType: "Network",
    phoneNumber: "09-987-2103",
    email: "ethan@example.com",
    status: "accepted",
  },
];
